# Generated by Django 4.0.4 on 2022-05-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
